Description:
  This template deploys an S3 bucket and CloudFront Distribution using the
  AWS CloudFormation service.
Parameters:
  S3BucketName:
    Type: String
    Default: my-s3-bucket
  HostedZoneName:
    Type: String
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  CertificateArn:
    Type: String
    Description: Insert ARN Certificate for used, only us-east-1
  SubdomainName:
    Type: String
    Description: Subdomain name for cloudformation
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: S3Bucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt S3Bucket.RegionalDomainName
            Id: s3-origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Join
            - .
            - - !Ref SubdomainName
              - !Ref HostedZoneName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        DefaultCacheBehavior:
          TargetOriginId: s3-origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        HttpVersion: http2
  SubdomainRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Join
        - .
        - - !Ref SubdomainName
          - !Ref HostedZoneName
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !GetAtt CloudFrontDistribution.DomainName